config/routes.rb
R20130308Tradr::Application.routes.draw do

  root :to => 'welcome#index'

  resources :users, :only => [:edit, :new, :create, :index]
  resources :stocks do
    collection do
      get 'quote/:symbol', :action => 'quote'
    end
  end

  get '/login'  => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/stock.rb
# == Schema Information
#
# Table name: stocks
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  symbol     :string(255)
#  user_id    :integer
#  quantity   :integer
#  price      :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Stock < ActiveRecord::Base
  attr_accessible :name, :symbol, :user_id, :quantity, :price
  belongs_to  :user, :inverse_of =>:stocks
  validates :quantity, :presence => true

  def position
    get_quote.lastTrade * self.quantity
  end

  def get_quote
    begin
      YahooFinance::get_quotes(YahooFinance::StandardQuote, self.symbol)[self.symbol]
    rescue
      puts "no good"
    end
  end

  before_save :buy_stock

  private
  def buy_stock
    quote = get_quote
    if quote.present?
      self.symbol = quote.symbol
      self.price = quote.lastTrade
      self.name = quote.name
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  balance         :decimal(, )
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :balance
  has_many :stocks, :inverse_of => :user
  has_secure_password

  def positions_total
    stocks.map(&:position).reduce(:+).to_f
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate

  private
  def authenticate
    @auth = User.find(session[:user_id]) if session[:user_id].present?
  end

  def check_if_logged_in
    redirect_to(root_path) if @auth.nil?
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.where(:email => params[:email]).first
    if user.present? && user.authenticate(params[:password]) #user and password match
      session[:user_id] = user.id #create the hash session, and set the userid to the userid of the user from the table.
      redirect_to(users_path)
    else
      flash[:notice] = 'Nope. Try again.'
      redirect_to(login_path)
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to(root_path)
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @stocks = @auth.stocks
  end

  def new
    @stock = Stock.new
  end

  def create #for this lab, new = buy
    @stock = Stock.create(params[:stock])
    @auth.stocks << @stock
  end

  def quote
    #symbol = Stock.get_quote(params[:symbol])
    symbol = Stock.where(:symbol => params[:symbol]).first
    lastTrade = symbol.get_quote.lastTrade
    render :json => {symbol: symbol.symbol, lastTrade:lastTrade, name: symbol.name}
    # symbol = Hash.new()
    # render :json => [symbol]
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :check_if_logged_in, :except => [:new, :create, :index]
  def index
    @users = User.all
    @stocks = Stock.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = @auth
    render :new
  end

  def create
    @user = User.create(params[:user])
    @users = User.all
  end

  def update
    @user = @auth
    if @user.update_attributes(params[:user])
      redirect_to(root_path)
    else
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->

<footer class="row">
  <div class="large-12 columns"><hr />
    <div class="row">

      <div class="large-6 columns">
        <p>&copy; Copyright yo momma</p>
        <% if @auth.present? %>
          <p>Logged in as: <%= @auth.email  %> </p>
        <% end %>
      </div>

      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="http://twitter.com/khalua">Twitter</a></li>
          <li><a href="http://yerko.com">Yerko</a></li>
        </ul>
      </div>

    </div>
  </div>
</footer>

<!-- End Footer -->

app/views/layouts/_nav.html.erb
<!-- Navigation -->

      <ul class="button-group round small">
        <li><a href="/" class="button">Home</a></li>
        <li><%= link_to('Users', users_path, :class => 'button') %></li>

        <% if @auth.present? %>
          <li><%= link_to('Stocks', stocks_path, :class => 'button') %></li>
          <li><%= link_to( @auth.name, login_path, :method => :delete, :confirm => 'Going to workout?', :class => 'button') %></li>

        <% else %>
          <li><%= link_to("Log in", login_path, :class => 'button') %></li>
          <li><%= link_to("Create Account", new_user_path, :class => 'button') %></li>
        <% end %>
      </ul>
<!-- End Navigation -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tradr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row">
  <div class="large-12 columns">

  <%= render :partial => "layouts/nav" %>

<h1>Tradr</h1>

<%= yield %>

  <%#= render :partial => "layouts/footer" %>


</div>
</div>
  <script>
    $(document).foundation();
  </script>
</body>
</html>

app/views/session/new.html.haml
.row
  .large-5.columns
    = form_tag '/login' do
      = label_tag 'email'
      = text_field_tag 'email', nil, :autofocus => true
      = label_tag 'password'
      = password_field_tag 'password'
      %br
      = submit_tag  'Login to Tradr', :class => 'button radius'
  .large-7.columns

app/views/stocks/_form.html.haml
.row
  .large-5.columns
    = form_for @stock, :remote => true do |f|
      = f.label :symbol
      = f.text_field :symbol, :autofocus => true
      = f.label :quantity
      = f.text_field :quantity
      %br
      = f.submit 'Buy Stock', :class => 'button radius success' , :id => 'buy_stock_button'
      = f.submit 'Cancel', :class => 'button alert radius' , :id => 'close_stock_form_button'
  .large-7.columns

app/views/stocks/_stocks.html.haml
%script
  var quotes = {};
#check_boxes
  = form_tag
  - @stocks.each do |stock|
    .check_boxes
      = label_tag stock.symbol
      .box= check_box_tag stock.symbol
      %script
        = "quotes['#{stock.symbol}'] = ({name:'#{stock.name}', symbol:'#{stock.symbol}', price:#{stock.price}})"
.clear

#graph

app/views/stocks/create.js.erb
$('#new_stock').empty();

app/views/stocks/index.html.haml
#buy_stock_button
  = link_to('Buy Stock', new_stock_path, :remote=> true, :class => 'button radius success', :id => 'show_new_stock_button')

#new_stock

= render(:partial => 'stocks')

#graphs

app/views/stocks/new.js.erb
$('#new_stock').append('<%=j render(:partial => 'form') %>');

app/views/users/_form.html.haml
.row
  .large-5.columns
    = form_for @user, :remote => true do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      = f.label :balance, 'Opening balance'
      = f.text_field :balance
      %br
      = f.submit :class => 'button radius' , :id => 'create_user_button'
      = f.submit 'Cancel', :class => 'button alert radius' , :id => 'close_user_form_button'
  .large-7.columns

app/views/users/_users.html.haml
#users_table
  %table
    %theader
      %tr
        %th Name
        %th Cash
        %th Positions
        %th Total
    %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= number_to_currency(user.balance)
        %td= number_to_currency(user.positions_total)
        %td= number_to_currency(user.balance + user.positions_total )

app/views/users/create.js.erb
$('#new_user').empty();
$('#users_table').empty();
$('#users_table').append( "<%=j render(:partial => 'users') %>" );

app/views/users/index.html.haml
= link_to('New User', new_user_path, :remote=> true, :class => 'button radius success')
#new_user

= render(:partial => 'users')

app/views/users/new.js.erb
$('#new_user').append('<%=j render(:partial => 'form') %>');